on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Check
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: ${{ github.repository_owner }}
      organization: ropensci
